### ISSUE TITLE
status

### ISSUE THREAD

**Issue by rogueturnip** [the-cookbook/mapper-js#1]
Is this package still being maintained?  Last version is Sept 2020.  If not is there another recommended package to use?

**Comment by themgoncalves** [comment]
Hello @rogueturnip, this repository is still being maintained. The updated are not that frequent as the overall implementation is stable. But in meanwhile, I'm working on a few improvements regarding typescript api usage.

If you have any feat. request or any other improvement, feel free to suggest.
