### ISSUE TITLE
husky not found

### ISSUE THREAD

**Issue by JBoetzkes** [the-cookbook/mapper-js#2]
Using @cookbook/mapper-js 1.1.0 there is an issue installing the library. 

npm ERR! code 127
npm ERR! path /home/plasmatic/alana-building/building-core/node_modules/@cookbook/mapper-js
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: 1: husky: not found

I was able to work around this by adding husky into the package manually and then doing another npm install. But, it seems there is a problem with the library installation.

**Comment by themgoncalves** [comment]
Thanks for the report, I will working on a fix soon.

**Comment by themgoncalves** [comment]
@JBoetzkes I just published the fix for it, you can find it working on the `v1.1.1`.
