### ISSUE TITLE
mapper not a function

### ISSUE THREAD

**Issue by rogueturnip** [the-cookbook/mapper-js#3]
Hi!  Just doing an update to the latest version and I'm getting a strange error.
```
const mapper = require("@cookbook/mapper-js");

    const mapping = mapper((map) => ({
      "address.city": map("city").value,
    }));
```
I'm getting this error
```
const mapping = mapper((map) => ({
                             ^
TypeError: mapper is not a function
```

Any thoughts?

**Comment by themgoncalves** [comment]
Hey @rogueturnip, you're missing a small thing on your import statement, the `.default` after the require :)

```js
const mapper = require("@cookbook/mapper-js").default;

const mapping = mapper((map) => ({
  "address.city": map("city").value,
}));
```


This will do the trick for you

**Comment by rogueturnip** [comment]
Great!  Thanks!  Didn't see this in the readme.

**Comment by themgoncalves** [comment]
It's not written there, but will include it in the next release. Thanks for the feedback!
